/**
 * Rótulos em português para os campos que chegam do backend.
 *
 * Vive fora da tela de rotinas porque qualquer lugar que exiba um registro
 * "cru" precisa do mesmo dicionário — sem ele, o nome do campo apareceria em
 * inglês para o usuário.
 */
export const FIELD_LABELS: Record<string, string> = {
  id: "Código", item_code: "Item", supplier_code: "Fornecedor", purchase_order_code: "Pedido de compra",
  purchase_order_item_code: "Linha do pedido", enterprise_code: "Empresa", warehouse_id: "Almoxarifado",
  description: "Descrição", notes: "Observações", status: "Situação", mask: "Máscara", quantity: "Quantidade",
  code: "Código", sequence: "Sequência", starts_at: "Início", ends_at: "Fim", start_from: "Iniciar em",
  valid_from: "Vigência inicial", valid_to: "Vigência final", reference_date: "Data de referência",
  __body: "Dados da operação",
  order_code: "Ordem", schedule_date: "Data da programação", start_time: "Início", end_time: "Fim",
  planned_qty: "Quantidade planejada", produced_qty: "Quantidade produzida", production_time: "Tempo de produção",
  priority: "Prioridade", bom_type: "Tipo de estrutura", created_by: "Usuário responsável",
  emission_date: "Data de emissão", delivery_date: "Data de entrega", delivery_date_firm: "Data de entrega confirmada",
  digit_date: "Data de digitação", customer_code: "Cliente", order_number: "Número do pedido",
  currency: "Moeda", currency_code: "Moeda", is_active: "Ativo", is_blocked: "Bloqueado",
  is_firm: "Confirmado", is_nfce: "NFC-e", requested_qty: "Quantidade solicitada",
  unit_price: "Preço unitário", attended_qty: "Quantidade atendida", cancelled_qty: "Quantidade cancelada",
  total_gross: "Total bruto", total_net: "Total líquido", payment_term_code: "Condição de pagamento",
  sales_table_code: "Tabela de venda", price_table_code: "Tabela de venda", policy_code: "Política comercial",
  commercial_analysis_status: "Situação da análise comercial", commission_pct: "Comissão (%)", additional_days: "Dias adicionais",
  financial_analysis_status: "Situação da análise financeira", release_status: "Situação da liberação",
  attended_reason: "Motivo do atendimento", attended_at: "Atendido em", delay_reason: "Motivo do atraso", delay_action: "Ação para o atraso",
  conference_status: "Situação da conferência", created_at: "Criado em", updated_at: "Atualizado em",
  updated_by: "Usuário que atualizou", representative_code: "Representante",
  sales_plan_code: "Plano de vendas", segment_code: "Segmento",
  market_segment_code: "Segmento de mercado", item_classification_code: "Classificação do item",
  is_primary: "Principal", is_default: "Padrão", postal_code: "CEP", city: "Cidade", state: "UF",
  street: "Logradouro", street_number: "Número", district: "Bairro",
  product_line_id: "Linha de produto", item_mask: "Máscara do item",
  block_reason: "Motivo do bloqueio", cancel_reason: "Motivo do cancelamento", balance: "Saldo", reason: "Motivo", action: "Ação",
  legacy_item_code: "Código anterior do item", new_date: "Nova data", old_date: "Data anterior",
  sales_order_code: "Pedido de venda", call_number: "Número do chamado", consumer_code: "Consumidor",
  call_type_code: "Tipo de chamado", contacted_at: "Data do contato", contact_type: "Tipo de contato",
  next_return_at: "Próximo retorno", user_code: "Usuário responsável", file_name: "Nome do arquivo",
  file_path: "Local do arquivo", content_type: "Tipo do arquivo", observation: "Observação",
  cost_source: "Fonte de custo", policy_scope: "Abrangência da política", policy_types: "Tipos da política",
  markup_pct: "Acréscimo (%)", margin_pct: "Margem (%)", max_margin_pct: "Margem máxima (%)",
  ideal_margin_pct: "Margem ideal (%)", margin_step_pct: "Intervalo de margem (%)",
  expenses_pct: "Despesas (%)", taxes_pct: "Impostos (%)", freight_pct: "Frete (%)",
  discount_pct: "Desconto (%)", min_margin_pct: "Margem mínima (%)",
  max_discount_pct: "Desconto máximo (%)", incidences_json: "Regras de incidência",
  name: "Nome", attribute: "Campo avaliado", operator: "Operador", value: "Valor", person_type: "Tipo de pessoa",
  call_code: "Chamado", direction: "Direção", in_warranty: "Em garantia",
  defect_group_code: "Grupo de defeito", defect_reason_code: "Motivo do defeito",
  responsible_user_code: "Usuário responsável", position: "Posição", situation: "Situação",
  opened_at: "Aberto em", return_date: "Data de retorno", visit_requested_date: "Data solicitada para visita",
  visit_returned_date: "Data do retorno da visita", sale_store_code: "Loja da venda",
  establishment_code: "Estabelecimento", technician_description: "Descrição do técnico",
  symptoms: "Sintomas", forwarded_store_code: "Loja encaminhada", subject: "Assunto", solution: "Solução",
  checklist_code: "Lista de verificação", returns: "Retornos", attachments: "Anexos",
  checklist_items: "Itens da lista de verificação", is_done: "Concluído", done_at: "Concluído em",
  phone_type: "Tipo de telefone", number: "Número", contact_code: "Contato", email: "E-mail", role: "Função",
  zip_code: "CEP", address: "Endereço", address_number: "Número", complement: "Complemento",
  knowledge_code: "Como conheceu", rg: "RG", cpf: "CPF", cnpj: "CNPJ", state_registration: "Inscrição estadual",
  // Roteiros / operações (VENT0115, VENT0202)
  is_standard: "Padrão", alternative: "Alternativa", route_id: "Roteiro", operation_id: "Operação",
  operation_code: "Código da operação", operation_name: "Nome da operação", standard_time: "Tempo padrão",
  setup_time: "Tempo de preparação", eff_time: "Tempo efetivo", effective_setup: "Preparação efetiva",
  effective_setup_time: "Preparação efetiva", effective_std_time: "Tempo padrão efetivo",
  effective_time: "Tempo efetivo", network: "Rede", operations: "Operações", resources: "Recursos",
  route: "Roteiro", critical_path: "Caminho crítico", total_hours: "Total (horas)",
  lead_time_hours: "Lead time (horas)", crew_size: "Equipe", labor_hours: "Horas de mão de obra",
  move_hours: "Horas de movimentação", queue_hours: "Horas de fila", run_base_qty: "Quantidade base",
  run_hours: "Horas de processamento", setup_hours: "Horas de preparação", work_center_id: "Centro de trabalho",
  work_center: "Centro de trabalho", overlap_pct: "Sobreposição (%)", predecessor_id: "Predecessora",
  successor_id: "Sucessora",
  // Máscaras de lote / série e expedição
  application: "Aplicação", classification_type: "Tipo de classificação", part_type: "Tipo de parte",
  date_format: "Formato de data", lot_mask_id: "Máscara de lote", size: "Tamanho",
  zero_on_year_change: "Zerar na virada de ano", current_value: "Valor atual",
  load_code: "Carga", carrier_code: "Transportadora", dispatch_box_code: "Caixa de despacho", box_code: "Caixa",
  shipment_code: "Romaneio", fiscal_exit_id: "Saída fiscal", nfe_number: "Número da NF-e", nfe_key: "Chave da NF-e",
  zone: "Zona", planned_ship_date: "Previsão de despacho", estimated_delivery: "Previsão de entrega",
  vehicle_plate: "Placa", driver_name: "Motorista", driver_document: "Documento do motorista",
  route_code: "Rota", origin: "Origem", destination: "Destino", active_only: "Somente ativas",
  // APS / produção
  resource_group_id: "Grupo de recurso", calendar_id: "Calendário", location: "Localização",
  is_critical: "Crítico", machine_cost_center_id: "Centro de custo da máquina", labor_cost_center_id: "Centro de custo da mão de obra",
  capacity_hours: "Horas de capacidade", order_ids: "Ordens", machine_ids: "Máquinas",
  work_center_ids: "Centros de trabalho", operation_ids: "Operações", resource_id: "Recurso",
  cost_center_id: "Centro de custo", function_name: "Função", is_supervisor: "Supervisor", is_manager: "Gerente",
  service_code: "Serviço", service_type: "Tipo de serviço", frequency_value: "Valor da frequência", frequency_unit: "Unidade da frequência",
  max_tolerance: "Tolerância máxima", implemented_on: "Implementado em", responsible_employee_ids: "Responsáveis",
  usage_description: "Uso", preparation_time: "Tempo de preparação", preparation_time_unit: "Unidade do tempo de preparação",
  brand: "Marca", is_preferred: "Preferencial", special_values: "Campos especiais", numeric_value: "Valor numérico",
  lot_return_mode: "Modo de retorno do lote", auto_issue_lots: "Baixa automática de lotes", movement_from: "Movimento de",
  movement_to: "Movimento até", stock_uom: "UM de estoque", controls_lot: "Controla lote", controls_address: "Controla endereço",
  inventory_group_type: "Tipo de grupo de inventário", automatic_issue_type: "Tipo de baixa automática", line_warehouse_id: "Almoxarifado da linha",
  is_wms: "WMS", intermediate_out_warehouse_id: "Almoxarifado intermediário de saída",
  employee_id: "Funcionário", contact_id: "Contato", function_id: "Função", service_id: "Serviço", field_id: "Campo",
  machine_id: "Máquina", weekday: "Dia da semana", start: "Início", end: "Fim", intervals: "Intervalos",
  downtime_type: "Tipo de parada",
  // Rótulos das rotinas operacionais: toda chave lida do backend precisa de
  // tradução aqui, senão humanLabel() cai no nome do campo em inglês.
  formula: "Fórmula", characteristic_id: "Característica", variable_id: "Variável",
  answers: "Respostas", parent_item_code: "Item pai", uom: "Unidade de medida",
  persist: "Gravar configuração", items: "Itens", is_special: "Especial",
  rejected_qty: "Qtde. rejeitada", destination_warehouse_id: "Almoxarifado de destino", period_start: "Início do período",
  period_end: "Fim do período", value_type: "Tipo do valor", parent_uom: "Unidade do item pai",
  child_item_code: "Item filho", parent_characteristic_id: "Característica do pai", parent_operator: "Operador do pai",
  child_characteristic_id: "Característica do filho", child_operator: "Operador do filho", target_table: "Tabela de destino",
  target_field: "Campo de destino", content: "Conteúdo", conditions: "Condições",
  material_spec: "Especificação do material", reference: "Referência", kind: "Tipo",
  is_required: "Obrigatório", min_value: "Valor mínimo", max_value: "Valor máximo",
  commercial_score: "Nota comercial", service_score: "Nota de atendimento", from: "De",
  tolerance_type: "Tipo de tolerância", applies_to: "Aplica-se a", serie: "Série",
  order_id: "Ordem", payload: "Conteúdo da mensagem", source: "Origem",
  step_id: "Etapa", sample_index: "Amostra", measured_value: "Valor medido",
  is_approved: "Aprovado", conform_qty: "Qtde. conforme", rework_qty: "Qtde. para retrabalho",
  restricted_qty: "Qtde. restrita", treatment: "Tratamento", affects_supplier_score: "Afeta a nota do fornecedor",
  move_stock: "Movimenta estoque", rejection_warehouse_id: "Almoxarifado de rejeição", approved_qty: "Qtde. aprovada",
  quarantine_warehouse_id: "Almoxarifado de quarentena", lines: "Linhas", incoterm: "Incoterm",
  exchange_rate: "Taxa de câmbio", apportion_basis: "Base de rateio", weight: "Peso",
  fob_unit_price: "Preço unitário FOB", expenses: "Despesas", expense_type: "Tipo de despesa",
  amount: "Valor", in_item_cost: "Compõe o custo do item", lot: "Lote",
  mask_composition: "Composição da máscara", include_description: "Incluir na descrição", special_data: "Dado especial",
  marketing: "Uso comercial", language: "Idioma", type: "Tipo",
  receiving_type: "Tipo de recebimento", is_drawing: "Gera desenho", is_load: "Compõe carga",
  default_answers: "Respostas padrão", preferred: "Preferencial", freight_type: "Tipo de frete",
  freight_value: "Valor do frete", tax_percent: "Percentual de imposto", rules: "Regras",
  ids: "Registros", time_unit: "Unidade de tempo", refresh_value: "Intervalo de atualização",
  digit: "Dígito", format: "Formato", model: "Modelo",
  creation_date: "Data de criação", revision: "Revisão", start_date: "Data de início",
  approved_by: "Aprovado por", approval_date: "Data de aprovação", is_current: "Vigente",
  interval_min: "Intervalo mínimo", tolerance_value: "Valor da tolerância", customer_id: "Cliente",
  title: "Título", instruction: "Instrução", tipo: "Tipo",
  numero_documento: "Número do documento", valor: "Valor", ranking: "Ordem de preferência",
  serial_number: "Número de série", justificativa: "Justificativa", data_emissao: "Data de emissão",
  cfop: "CFOP", valor_frete: "Valor do frete", valor_seguro: "Valor do seguro",
  actual_hours: "Horas realizadas", record_type: "Tipo de registro", basis: "Base",
  inspection_warehouse_id: "Almoxarifado de inspeção", steps: "Etapas", inspection_name: "Nome da inspeção",
  appointment_mode: "Modo de apontamento", emits_label: "Emite etiqueta", sample_qty: "Qtde. da amostra",
  acceptance_qty: "Qtde. de aceitação", rejection_qty: "Qtde. de rejeição", attributes: "Atributos",
  quality_score: "Nota de qualidade", delivery_score: "Nota de entrega", total_receipts: "Total de recebimentos",
  rejected_receipts: "Recebimentos rejeitados", late_receipts: "Recebimentos em atraso", scope: "Abrangência",
  auto_approve_max: "Aprovação automática até", block_above: "Bloquear acima de", domain: "Domínio",
  param_key: "Parâmetro", param_value: "Valor do parâmetro", message_type: "Tipo de mensagem",
  qty_tolerance: "Tolerância de quantidade", price_tolerance: "Tolerância de preço", homologated_min: "Mínimo de homologados",
  conditional_min: "Mínimo de condicionais", category: "Categoria", valid_until: "Válido até",
  country: "País", translation: "Tradução", set_id: "Conjunto",
  affects_price: "Afeta o preço", controls_goals: "Controla metas", field_source: "Campo de origem",
  option_true: "Rótulo para \"Sim\"", option_false: "Rótulo para \"Não\"", restrict: "Restringir respostas",
  variable_ids: "Variáveis", description_type_id: "Tipo de descrição", order_index: "Ordem",
  show_characteristic: "Mostrar característica", show_mask: "Mostrar máscara", desc_type: "Tipo de texto",
  text: "Texto", line_break: "Quebra de linha", percent: "Percentual",
  move: "Mover", purchase_requisition_code: "Requisição de compra", movement_type: "Tipo de movimento",
  occurred_at: "Ocorrido em", reference_type: "Tipo de referência", reference_code: "Código da referência",
  idempotency_key: "Chave de controle de duplicidade", from_uom: "Unidade de origem", to_uom: "Unidade de destino",
  factor: "Fator de conversão", maintenance_order_id: "Ordem de manutenção", contacts: "Contatos",
  functions: "Funções", credit_limit: "Limite de crédito", services: "Serviços",
  list_only_active_resources: "Listar apenas recursos ativos", recipient: "Destinatário", distributed_at: "Distribuído em",
  drawing_code: "Desenho", replicate_drawing_revision: "Replicar revisão do desenho", plan_code: "Plano",
  initial_order_number: "Número inicial da ordem", generate_llc: "Gerar nível mais baixo (LLC)", interval_max: "Intervalo máximo",
  expected: "Esperado", actual: "Realizado", param_number: "Número do parâmetro",
  nome: "Nome", suframa: "Suframa", codigo_municipio: "Código do município",
  regime_tributario: "Regime tributário", data_inicial: "Data inicial", data_final: "Data final",
  indicador_situacao: "Indicador de situação", contabilista_nome: "Nome do contabilista", contabilista_cpf: "CPF do contabilista",
  contabilista_crc: "CRC do contabilista", contabilista_cnpj: "CNPJ do contabilista", participantes: "Participantes",
  unidades: "Unidades", itens: "Itens", documentos_fiscais: "Documentos fiscais",
  inventario: "Inventário", chave_acesso: "Chave de acesso", context: "Contexto",
  channel: "Canal", parceiro_id: "Parceiro", conta_bancaria_id: "Conta bancária",
  data_adiantamento: "Data do adiantamento", valor_original: "Valor original", descricao: "Descrição",
  conta_tipo: "Tipo de conta", conta_id: "Conta", data_aplicacao: "Data de aplicação",
  config: "Configuração", titulos: "Títulos", nosso_numero: "Nosso número",
  vencimento: "Vencimento", emissao: "Emissão", sacado_nome: "Nome do sacado",
  sacado_tipo: "Tipo do sacado", sacado_documento: "Documento do sacado", sacado_endereco: "Endereço do sacado",
  sacado_bairro: "Bairro do sacado", sacado_cidade: "Cidade do sacado", sacado_uf: "UF do sacado",
  sacado_cep: "CEP do sacado", default_financial_account: "Conta financeira padrão", unique_item_code_per_supplier: "Código do item único por fornecedor",
  requires_financial_account: "Exigir conta financeira", purchase_supplier_type_id: "Tipo de fornecedor de compra", copy_obs_to_purchase_order: "Copiar observação para o pedido de compra",
  copy_obs_to_entry_invoice: "Copiar observação para a nota de entrada", homologation_default: "Homologação padrão", use_stock_uom: "Usar a unidade de estoque",
  generic_supplier_code: "Fornecedor genérico", default_due_base_date: "Data-base padrão de vencimento", table_code: "Tabela",
  overwrite: "Sobrescrever existentes", selections: "Seleções", source_type: "Tipo de origem",
  source_id: "Origem", source_item_id: "Item de origem", target_item_id: "Item de destino",
  mode: "Modo", price: "Preço", ume: "Unidade de estoque",
  umc: "Unidade de compra", price_conv: "Preço convertido", blocked: "Bloqueado",
  item_codes: "Itens", plan_id: "Plano", empresa_id: "Empresa",
  empresa: "Empresa", livros: "Livros", chave_nfe: "Chave da NF-e",
  numero_inicial: "Número inicial", numero_final: "Número final", data_saida: "Data de saída",
  cnpj_destinatario: "CNPJ do destinatário", razao_social_destinatario: "Razão social do destinatário", ie_destinatario: "Inscrição estadual do destinatário",
  uf_destinatario: "UF do destinatário", tipo_pessoa: "Tipo de pessoa", natureza_operacao: "Natureza da operação",
  valor_desconto: "Valor do desconto", origem_mercadoria: "Origem da mercadoria", item_overrides: "Exceções por item",
  numero_cte: "Número do CT-e", data_entrada: "Data de entrada", cnpj_emitente: "CNPJ do emitente",
  razao_social_emitente: "Razão social do emitente", valor_outros: "Outros valores", valor_total: "Valor total",
  valor_icms: "Valor do ICMS", base_icms: "Base do ICMS", aliq_icms: "Alíquota do ICMS",
  tipo_rateio: "Tipo de rateio", reason_code: "Motivo", reason_description: "Descrição do motivo",
  eligibility_status: "Situação da elegibilidade", eligibility_reason: "Motivo da elegibilidade", sla_due_at: "Prazo do SLA",
  product_cost: "Custo do produto", freight_cost: "Custo do frete", service_cost: "Custo do serviço",
  call_item_code: "Item do chamado", lot_number: "Número do lote", requested_destination: "Destino solicitado",
  correlation_id: "Identificador de correlação", authorization_number: "Número da autorização", reverse_carrier_code: "Transportadora da logística reversa",
  reverse_tracking_code: "Rastreio da logística reversa", inspection_notes: "Observações da inspeção", fiscal_document_key: "Chave do documento fiscal",
  stock_movement_code: "Movimento de estoque", component_item_code: "Item componente", area: "Área",
  event_date: "Data do evento",
};

/** Rótulo de um campo; sem tradução, devolve o nome legível do próprio campo. */
export function fieldLabel(key: string): string {
  return FIELD_LABELS[key] ?? key.split("_").map((part) => (part ? part[0].toUpperCase() + part.slice(1) : part)).join(" ");
}
